### ISSUE TITLE
Dica spring validator

### ISSUE THREAD

**Issue by arthurs159** [fernandocastrogon/epicrm-api#1]
Ei Fernando, beleza?

Vejo que você utiliza o `@Column`, tem uma outra alternativa muito legal, que é o spring validator, da uma pesquisada, acredito que seja bem melhor utiliza-la
![image](https://user-images.githubusercontent.com/77133022/206039848-06377ae6-3f5b-4041-ae97-eaf76033638a.png)

Daí é possivel colocar o `@NotNull` ao inves do `@Column`

**Comment by fernandocastrogon** [comment]
Oi Arthur,

Muito obrigado pela dica, consegui utilizar o Spring Validator e testar!

    @NotEmpty
    private String descricao;

    @NotNull
    private int ca;

    @Future (message = "A validade está vencida")
    @JsonFormat(pattern = "dd-MM-yyyy")
    private LocalDate validadeCa;

    @NotEmpty
    private String categoria;

    @NotNull
    private int quantidadeEstoque;

**Comment by fernandocastrogon** [comment]
Oi Arthur,

Muito obrigado pela dica, consegui utilizar o Spring Validator e testar!

    @NotEmpty
    private String descricao;

    @NotNull
    private int ca;

    @Future (message = "A validade está vencida")
    @JsonFormat(pattern = "dd-MM-yyyy")
    private LocalDate validadeCa;

    @NotEmpty
    private String categoria;

    @NotNull
    private int quantidadeEstoque;
